name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
          Thanks for taking the time to fill out this bug  report.
  - type: textarea
    id: what-happened
    attributes:
      label: What unexpectedly happened, and what did you expect to happen?
      placeholder: Tell us what you found.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce (optional)
      description: Let us know step-by-step how to reproduce the issue.
      value: |
        1. go to cve.org website 
        2. select ....
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on? (optional)
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
